config/routes.rb
Grouper::Application.routes.draw do
  resources :user_sessions, :users, :memberships

  resources :groups do
    collection do
      get 'available'
    end
  end

  resource :account, :controller => 'users'

  root :to => 'welcome#index'
  

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :subgroups, :class_name => "Group", :foreign_key => "parent_id"
  belongs_to :parent, :class_name => "Group", :foreign_key => "parent_id"
  has_many :memberships
  has_many :users, :through => :memberships

  validates_presence_of :name, :slug
  validates_uniqueness_of :name, :slug

  attr_accessible :name, :parent_id, :slug

  before_validation :update_slug

  def self.available(user_id)
    joins("left join memberships on groups.id = memberships.group_id and memberships.user_id = #{user_id}").where("memberships.id is null")
  end

  def self.find_by_admin_rights(user_id)
    joins("left join memberships on groups.id = memberships.group_id", "left join roles on memberships.role_id = roles.id").where("roles.rank >= 10").where("memberships.user_id = ?", user_id)
  end

  def self.find_with_no_parent
    where(parent_id: nil).order(:name)
  end

private

  def update_slug
    self.slug = name.gsub(' ','').underscore unless name.nil?
  end
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :group
  belongs_to :user
  belongs_to :role

  validates_presence_of :group_id, :user_id, :role_id
  validates_uniqueness_of :group_id, :scope => :user_id

  attr_accessible :group_id, :user_id, :group, :user
  attr_protected :role_id
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :memberships

  validates_presence_of :name
  validates_uniqueness_of :name

  #TODO: create a scoped association by group
  attr_accessible :name, :rank


  def self.find_by_membership(group_id, user_id)
    Membership.where(user_id: user_id, group_id: group_id).first.role
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic

  has_many :memberships
  has_many :groups, :through => :memberships
  
  validates_presence_of :email, :first_name, :last_name, :gender
  validates_uniqueness_of :email

  attr_accessible :email, :first_name, :gender, :last_name, :password, :password_confirmation
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user_session, :current_user, :is_group_admin

private
  def current_user_session
    return @current_user_session if defined?(@current_user_session)
    @current_user_session = UserSession.find
  end

  def current_user
    return @current_user if defined?(@current_user)
    @current_user = current_user_session && current_user_session.user
  end

  def is_group_admin(group_id)
    return false if current_user.nil?
    Role.find_by_membership(group_id, current_user.id).rank >= 10
  end

protected
  def authenticate
    return redirect_to root_path if current_user.nil?
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :authenticate, :except => [:show, :index]

  def index
    @groups = Group.find_with_no_parent
  end

  def available
    @groups = Group.available(current_user.id)
  end

  def show
    @group = Group.find(params[:id])
    if (current_user_session)
      @membership = @group.memberships.find_by_user_id(current_user.id)
    end
  end

  def new
    @group = Group.new
    @parent_groups = Group.find_with_no_parent.find_by_admin_rights(current_user.id)
  end

  def create
    @group = Group.new(params[:group])
    if @group.save
      membership = Membership.new(user_id: current_user.id, group_id: @group.id)
      membership.role_id = Role.find_by_name("GroupAdmin").id
      if membership.save
        redirect_to group_path(@group), :notice => "Group was created successfully"
      else
        flash[:notice] = "Something went wrong"
      end
    else
      render :action => :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    @group.update_slug
    if @group.update_attributes(params[:group])
      flash[:notice] = "Group was updated successfully"
      redirect_to group_path(@group)
    else
      render :action => :edit
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to root_path
  end
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_filter :authenticate

  def index
    @memberships = Membership.where(:user_id => current_user.id)
  end

  def show
    @membership = Membership.find(params[:id])
  end

  def new
    @membership = Membership.new
  end

  def create
    membership = Membership.new
    membership.group_id = params[:group_id]
    membership.user_id = current_user.id
    membership.role_id = Role.find_by_name("User").id
    if membership.save
      flash[:notice] = "Successfully joined the group"
      redirect_to group_path(membership.group_id)
    else
      render :action => :new
    end
  end

  def destroy
    @membership = Membership.find(params[:id])
    @membership.destroy
    redirect_to groups_path    
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
    @user_session = UserSession.new
  end

  def create
    @user_session = UserSession.new(params[:user_session])
    if @user_session.save
      flash[:notice] = "Login successful"
      redirect_to root_url
    else
      render :action => :new
    end
  end

  def destroy
    current_user_session.destroy
    flash[:notice] = "Logout successful"
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = 'Your account has been created'
      redirect_to root_url
    else
      render :action => :new
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/groups/_form.html.haml
= simple_form_for @group, :html => { :class => 'form-horizontal' } do |f|
  = f.input :name
  = f.input :parent_id, :collection => parent_groups, :label_method => :name, :value_method => :id, :prompt => "Select a parent group (optional)"
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), groups_path, :class => 'btn'
- parent_groups.each do |pg|
  .parent
    = pg.name

app/views/groups/_group.html.haml
.group
  %h3=group.name
  = link_to "View", group_path(group)

app/views/groups/available.html.haml
- model_class = Group.new.class
%h1=t '.title', :default => "Available Groups"
= render :partial => 'group', :collection => @groups

app/views/groups/edit.html.haml
- model_class = @group.class
%h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/groups/index.html.haml
- model_class = Group.new.class
%h1=t '.title', :default => model_class.model_name.human.pluralize
= render :partial => 'group', :collection => @groups

app/views/groups/new.html.haml
- model_class = @group.class
%h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render "form", :parent_groups => @parent_groups

app/views/groups/show.html.haml
- model_class = @group.class
%h1=@group.name

.member-actions
  - if @membership
    = link_to "Leave group", membership_path(@membership), :method => :delete, :confirm => 'Are you sure?', :class => 'btn'
  - else
    = link_to "Join group", {:controller => "memberships", :action => "create", :group_id => @group.id}, {:method => :post, :class => 'btn'}

- if is_group_admin(@group.id)
  .form-actions
    = link_to t('.edit', :default => t("helpers.links.edit")), edit_group_path(@group), :class => 'btn'
    = link_to t('.destroy', :default => t("helpers.links.destroy")), group_path(@group), :method => "delete", :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-danger'

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Grouper"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/favicon.ico" rel="shortcut icon")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114")

  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container-fluid
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="#") Grouper
          .container.nav-collapse
            %ul.nav
              - if current_user
                %li= link_to "Create Group", new_group_path
                %li= link_to "My Groups", memberships_path
              %li= link_to "Find Groups", available_groups_path
            - if current_user
              = link_to "My Account", account_path
              = link_to "Sign Out", user_session_path(current_user), :method => :delete
            - else
              = link_to "Sign In", new_user_session_path
              = link_to "Register", new_account_path
              
    .container-fluid

      .row-fluid
        .span3
          .well.sidebar-nav
            %ul.nav.nav-list
              %li.nav-header Sidebar
              %li= link_to "Link 1", "/path1"
              %li= link_to "Link 2", "/path2"
              %li= link_to "Link 3", "/path3"
        .span9
          - if flash[:error]
            %p.error= flash[:error]
          - if flash[:notice]
            %p.error= flash[:notice]
          = yield
    
      %footer
        %p &copy; Company 2012
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"


app/views/memberships/_form.html.haml
= simple_form_for @membership, :html => { :class => 'form-horizontal' } do |f|
  = f.input :group_id
  = f.input :user_id
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), memberships_path, :class => 'btn'

app/views/memberships/edit.html.haml
- model_class = @membership.class
%h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/memberships/index.html.haml
- model_class = Membership.new.class
%h1=t '.title', :default => "My Groups"
- @memberships.each do |membership|
  .membership
    %h3=membership.group.name
    =link_to "View", group_path(membership.group)

app/views/memberships/new.html.haml
- model_class = @membership.class
%h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/memberships/show.html.haml
- model_class = @membership.class
%h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:group_id) + ':'
  %br
  = @membership.group_id
%p
  %strong= model_class.human_attribute_name(:user_id) + ':'
  %br
  = @membership.user_id

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), memberships_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_membership_path(@membership), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), membership_path(@membership), :method => "delete", :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-danger'

app/views/user_sessions/_form.html.haml
= simple_form_for @user_session, :html => { :class => 'form-horizontal' } do |f|
  = f.input :email
  = f.input :password
  = f.check_box :remember_me
  .form-actions
    = f.submit "Login"

app/views/user_sessions/new.html.haml
- model_class = @user_session.class
%h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/users/_form.html.haml
= simple_form_for @user, :html => { :class => 'form-horizontal' } do |f|
  = f.input :first_name
  = f.input :last_name
  = f.input :email
  = f.input :password, :required => true
  = f.input :password_confirmation, :required => true
  = f.input :gender, :collection => [['Female', 'f'], ['Male', 'm']], :as => :radio_buttons
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), users_path, :class => 'btn'

app/views/users/edit.html.haml
- model_class = @user.class
%h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/users/index.html.haml
- model_class = User.new.class
%h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:first_name)
      %th= model_class.human_attribute_name(:last_name)
      %th= model_class.human_attribute_name(:email)
      %th= model_class.human_attribute_name(:password_salt)
      %th= model_class.human_attribute_name(:gender)
      %th= model_class.human_attribute_name(:persistence_token)
      %th= model_class.human_attribute_name(:crypted_password)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @users.each do |user|
      %tr
        %td= link_to user.id, user_path(user)
        %td= user.first_name
        %td= user.last_name
        %td= user.email
        %td= user.password_salt
        %td= user.gender
        %td= user.persistence_token
        %td= user.crypted_password
        %td=l user.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(user), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(user), :method => :delete, :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_user_path, :class => 'btn btn-primary'

app/views/users/new.html.haml
- model_class = @user.class
%h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/users/show.html.haml
- model_class = @user.class
%h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:first_name) + ':'
  %br
  = @user.first_name
%p
  %strong= model_class.human_attribute_name(:last_name) + ':'
  %br
  = @user.last_name
%p
  %strong= model_class.human_attribute_name(:email) + ':'
  %br
  = @user.email
%p
  %strong= model_class.human_attribute_name(:password_salt) + ':'
  %br
  = @user.password_salt
%p
  %strong= model_class.human_attribute_name(:gender) + ':'
  %br
  = @user.gender
%p
  %strong= model_class.human_attribute_name(:persistence_token) + ':'
  %br
  = @user.persistence_token
%p
  %strong= model_class.human_attribute_name(:crypted_password) + ':'
  %br
  = @user.crypted_password

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), users_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(@user), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(@user), :method => "delete", :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-danger'